version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    container_name: pfm-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pfm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: pfm-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Odoo 16.0
  odoo:
    image: odoo:16.0
    container_name: pfm-odoo
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8069:8069"
    volumes:
      - ./odoo/addons:/mnt/extra-addons
      - ./odoo/config:/etc/odoo
      - odoo_data:/var/lib/odoo
    environment:
      - HOST=postgres
      - USER=postgres
      - PASSWORD=postgres
    command: -- --dev=reload

  # Bank Adapter Service
  bank-adapter:
    build:
      context: ./services/bank-adapter
      dockerfile: Dockerfile
    container_name: pfm-bank-adapter
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8001:8001"
    volumes:
      - ./services/bank-adapter:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/bank_adapter
      - REDIS_URL=redis://redis:6379/0
    command: uvicorn bank_adapter.main:app --host 0.0.0.0 --port 8001 --reload

  # API Gateway
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    container_name: pfm-api-gateway
    depends_on:
      - bank-adapter
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./services/api-gateway:/app
    environment:
      - REDIS_URL=redis://redis:6379/1
      - BANK_ADAPTER_URL=http://bank-adapter:8001
      - ODOO_URL=http://odoo:8069
    command: uvicorn api_gateway.main:app --host 0.0.0.0 --port 8000 --reload

  # MinIO (S3-compatible storage for development)
  minio:
    image: minio/minio:latest
    container_name: pfm-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  postgres_data:
  redis_data:
  odoo_data:
  minio_data: